language: go

go:
  - 1.5
  - 1.6
  - tip

addons:
  apt:
    packages:
      - make

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/wgo/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/wgo/_workspace/bin:$PATH"
  - go get -u github.com/skelterjohn/wgo 

script:
  - make test
  - make
